#! /bin/bash

OPAM=${1:-$(which opam)}
if [ ! -e $OPAM ]; then
	echo "OPAM not found. Call as install-from-scratch <path to OPAM>"
	exit 2
fi

$OPAM init
$OPAM switch 4.02.1
eval $($OPAM config env)
$OPAM install yojson pcre kaputt csv cow lwt ocamlgraph batteries cohttp camomile bolt
exec ocamlbuild -use-ocamlfind testoracle.otarget
